### ISSUE TITLE
Can't use Init Image 

### ISSUE THREAD

**Issue by Adolfiux** [Rakile/deforumation#10]
I'm trying to use an initial image using deforumation, but the video is just creating a new image based on the prompt

**Comment by lainollll** [comment]
But you se the init image when you start to generate?

**Comment by Adolfiux** [comment]
> But you se the init image when you start to generate? 

No, the IA makes a random image using the info on the prompt, but doesn't load the init image to make a variation.

**Comment by kabachuha** [comment]
@Adolfiux what is your init_strength? (see Deforum's Init tab)

**Comment by Adolfiux** [comment]
> @Adolfiux what is your init_strength? (see Deforum's Init tab)

I am currently using 0.8. I have already made some videos without deforumation using the initial image, but I am unable to do so when using deforumation
