### ISSUE TITLE
Nothing happens after python mediator.py

### ISSUE THREAD

**Issue by amiremami** [Rakile/deforumation#3]
After writing this command, nothing happens:

https://i.imgur.com/4L9jWi7.png

Thanks

**Comment by amiremami** [comment]
Then got this, not sure if this error is separate thing or it's because the mediator command didn't work earlier:

https://i.imgur.com/4uTMdOg.png

**Comment by amiremami** [comment]
Thanks a lot my friend, everything works smoothly now, the new update is great! Just, is there any possibility that you show each new frame on deforumation panel? So, we can track the animation from your panel instead of Automatic?

**Comment by lainollll** [comment]
> Thanks a lot my friend, everything works smoothly now, the new update is great! Just, is there any possibility that you show each new frame on deforumation panel? So, we can track the animation from your panel instead of Automatic?

Yes , having the frame inside deforumation is something we have talked about amongst hundreds if other ideas. But first we want to se if deforumation gains any community, and users. otherwise its to much work :)
