### ISSUE TITLE
IDAT CRC ERROR

### ISSUE THREAD

**Issue by amiremami** [Rakile/deforumation#4]
Hey, sometimes I get these:

![image](https://user-images.githubusercontent.com/15929497/229613891-c01ef0b7-6e05-41f3-9edd-2b30f4c038f3.png)

![image](https://user-images.githubusercontent.com/15929497/229613921-60e4daa6-d345-4a68-893b-e41cd29dace3.png)

Also, tomorrow will post some videos on social media with your tool ❤️

Thanks

**Comment by lainollll** [comment]
The deforumation.py is updated should fix your issue.
