### ISSUE TITLE
Add Cadence control

### ISSUE THREAD

**Issue by kabachuha** [Rakile/deforumation#7]
Please, it would be a really nice feature here

**Comment by Rakile** [comment]
Yeah, it would among other parameters. Just promised @hithere on Deforum not to change anything else before a decision has been made how to integrate the communication into Deforum. If nothing happens in a week or two, I'll just keep on uggly hack things ;P

**Comment by amiremami** [comment]
@kabachuha Are you guys implementing this in Deforum? That would be great.

**Comment by lainollll** [comment]
> @kabachuha Are you guys implementing this in Deforum? That would be great.

yes

**Comment by Rakile** [comment]
> Please, it would be a really nice feature here

It has been done!

**Comment by Rakile** [comment]
It has been done

**Comment by kabachuha** [comment]
Thank you! 💜
